### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by rpoleski** [rachel3834/microlensing-online#15]
In [links](http://microlensing-source.org/links/) there are a few links that are given twice. The linked "OGLE photometry database" is from OGLE-II. The OGLE-III data are also public: [see ftp](ftp://ftp.astrouw.edu.pl/ogle/ogle3/maps/blg/). Also please consider linking UKIRT microlensing data release.

**Comment by rpoleski** [comment]
I've meant this FTP: ftp://ftp.astrouw.edu.pl/ogle/ogle3/maps/blg/

**Comment by rachel3834** [comment]
I've clarified these links and added a link to the UKIRT data as well.  They can be found under the Resources -> Links section. Thanks for raising the issue.
