### ISSUE TITLE
links to Roman Transients 2022 conference

### ISSUE THREAD

**Issue by rpoleski** [rachel3834/microlensing-online#17]
I suggest to add links in Resources section:

[https://conference.ipac.caltech.edu/romantimedomain/](https://conference.ipac.caltech.edu/romantimedomain/)

[https://www.youtube.com/playlist?list=PL460A0YI_JsAVIE-llqdGM7plKF1QbQxk](https://www.youtube.com/playlist?list=PL460A0YI_JsAVIE-llqdGM7plKF1QbQxk)

**Comment by rachel3834** [comment]
I have added these links under the Resources -> Links page, along side the links to other meetings. 
Thanks for the suggestion.
